[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [
    "img", "-t", "outer",
    "--transition-duration", "1",
    "--transition-step", "255",
    "--transition-fps", "144",
    "-f", "Nearest"
]
set = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[templates.hyprland]
input_path = "~/.dotfiles/store/$matugen/templates/hyprland.conf"
output_path = "~/.config/matugen/out/hyprland.conf"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/matugen/out/ax-shell.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[templates.zeditor]
input_path = "~/.dotfiles/store/$matugen/templates/zed.json"
output_path = "~/.config/zed/themes/matugen.json"
